# Generated by Django 5.1 on 2025-01-06 09:47

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0003_alter_user_gender_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about_me",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                default="cover.jpg",
                null=True,
                upload_to=userauths.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to=userauths.models.user_directory_path,
            ),
        ),
    ]
