# Generated by Django 5.1 on 2025-01-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0004_alter_profile_about_me_alter_profile_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
