# Generated by Django 5.1 on 2025-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0005_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
