# Generated by Django 5.1 on 2025-01-16 08:15

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_chatmessage_receiver_alter_chatmessage_sender_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["-date"], "verbose_name_plural": "Personal Chat"},
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.CharField(max_length=10000000000),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="mid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijklmnopqrstuvxyz",
                length=10,
                max_length=25,
                prefix="",
            ),
        ),
    ]
